### PR TITLE
Deploy application to AWS

### PR DESCRIPTION
**Pull request by ongyongen**
- Add Dockerfile and docker-compose file to containerize the application
- Add terraform scripts for the provisioning of S3 buckets and Cloudfront

### CODE REVIEW

**Comment by JiaEn182445u** [comment]
I recommend that we separate the terraform scripts into different files based on best practises 
https://developer.hashicorp.com/terraform/language/modules/develop/structure

**Comment by ongyongen** [comment]
> I recommend that we separate the terraform scripts into different files based on best practises https://developer.hashicorp.com/terraform/language/modules/develop/structure

Thanks Jia En! I did not previously consider this but separating the script into different files will definitely make our code more readable :)

**Comment by JiaEn182445u** [comment]
The new changes looks good! No other comments from me.

**Review by JiaEn182445u — APPROVED** [review]
Looks good!

**Pull request merged**
